version: '3.4'

services:
  push:
    image: ${DOCKER_REGISTRY}/${IMAGE_NAME}
    build:
      context: .
      dockerfile: src/csharppush/Dockerfile
  dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "compose",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-dapr-grpc-port", "50002",
     "-config", "/mount/config/collector_config.yaml",
     "-components-path", "/mount/components"]
    volumes:
        - mydata:/mount
    depends_on:
      - push
    network_mode: "service:push"
  otel:
    image: otel/opentelemetry-collector-contrib-dev:latest
    ports: 
      - 55678
    command: ["./otelcontribcol",
     "--config=/mount/config/otel-collector-config.yaml"]
    volumes:
      - mydata:/mount
    network_mode: "service:push"
volumes:
  mydata:
    driver: azure_file
    driver_opts:
      share_name: pushdapr
      storage_account_name: staticdapr
