on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
        
        - name: Install Docker Compose CLI
          run: curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
        
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Login Regestry'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
                      
        - name: 'Push Image to Registry'
          env: 
            IMAGE_NAME: '${{ secrets.REGISTRY_LOGIN_SERVER }}/daprpush'
          run: |
            echo $IMAGE_NAME
            docker build -f "./src/csharppush/Dockerfile" -t '$IMAGE_NAME:v${{ github.run_number }}" -t '$IMAGE_NAME:latest' .
            docker image push $IMAGE_NAME --all-tags
           
        - name: "login docker azure"
          run: "docker login azure --client-id $AZURE_CLIENT_ID --client-secret $AZURE_CLIENT_SECRET --tenant-id $AZURE_TENANT_ID"
          env:
            AZURE_TENANT_ID: '${{ secrets.AZURE_TENANT_ID }}'
            AZURE_CLIENT_ID: '${{ secrets.REGISTRY_USERNAME }}'
            AZURE_CLIENT_SECRET: '${{ secrets.REGISTRY_PASSWORD }}'
           
        - name: "Create an aci context"
          run: 'docker context create aci --subscription-id $AZURE_SUBSCRIPTION_ID --resource-group ${{ secrets.RESOURCE_GROUP }} acicontext'
          env:
            AZURE_SUBSCRIPTION_ID: '${{ secrets.AZURE_SUBSCRIPTION_ID }}'
            
        - name: "Compose Up"
          run: docker compose up -c acicontext
          env:
            IMAGE_NAME: 'daprpush:${{ github.sha }}'
            DOCKER_REGISTRY: '${{ secrets.REGISTRY_LOGIN_SERVER }}'
            APPINSIGHTS_INSTRUMENTATIONKEY: '${{ secrets.APPINSIGHTS_INSTRUMENTATIONKEY }}'  

 

